# Generated by Django 5.2.18 on 2026-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="for_friend",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="friend_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="friend_first_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="order",
            name="friend_last_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="order",
            name="friend_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="order",
            name="friend_photo",
            field=models.ImageField(blank=True, null=True, upload_to="friends/"),
        ),
        migrations.AddField(
            model_name="order",
            name="friend_sexe",
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
