# Generated by Django 5.2.18 on 2026-10-09 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=80, verbose_name="Nom de l'entreprise"),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Slogan / activité"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=80, verbose_name="Nom du contact"),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Fonction"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Site web"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Adresse"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="cards/", verbose_name="Logo"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#059669", "Vert"),
                            ("#1d4e89", "Bleu"),
                            ("#ea580c", "Orange"),
                            ("#7c3aed", "Violet"),
                            ("#be123c", "Rouge"),
                            ("#0f172a", "Noir"),
                        ],
                        default="#059669",
                        max_length=7,
                        verbose_name="Couleur",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
