# Generated by Django 6.1.1 on 2026-09-23 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('utilise', 'Utilisé'), ('annule', 'Annulé')], default='valide', max_length=20)),
                ('achete_le', models.DateTimeField(auto_now_add=True)),
                ('spectateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to=settings.AUTH_USER_MODEL)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='events.tickettype')),
            ],
            options={
                'ordering': ['-achete_le'],
            },
        ),
    ]
