# Generated by Django 6.1.1 on 2026-09-25 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='commission_montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='commission_pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ticket',
            name='montant_net_organisateur',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='montant_paye',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='moyen_paiement',
            field=models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('orange_money', 'Orange Money'), ('carte', 'Carte bancaire'), ('paypal', 'PayPal')], max_length=20),
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('moyen_paiement', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('orange_money', 'Orange Money'), ('carte', 'Carte bancaire'), ('paypal', 'PayPal')], max_length=20)),
                ('destination', models.CharField(blank=True, help_text='Numéro Mobile Money ou identifiant du moyen choisi', max_length=100)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='reussi', max_length=20)),
                ('demande_le', models.DateTimeField(auto_now_add=True)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-demande_le'],
            },
        ),
    ]
