# Generated by Django 6.1.1 on 2026-10-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_commission_montant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fedapay_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('valide', 'Valide'), ('utilise', 'Utilisé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
