# Generated by Django 6.1.1 on 2026-09-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.CharField(blank=True, default='Bénin', max_length=100),
        ),
    ]
