# Generated by Django 6.1.1 on 2026-10-01 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Gratuit'), ('PRO', 'Pro')], default='FREE', max_length=10)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='actif', max_length=20)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, help_text='Fin de la période payée en cours (plan PRO uniquement).', null=True)),
                ('fedapay_transaction_id', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('organisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
            },
        ),
    ]
