# Generated by Django 6.1.1 on 2026-09-23 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('visuel', models.ImageField(blank=True, null=True, upload_to='evenements/visuels/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='evenements/logos/')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('date_limite_achat', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='publie', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantite_disponible', models.PositiveIntegerField(default=0)),
                ('quantite_vendue', models.PositiveIntegerField(default=0)),
                ('couleur_badge', models.CharField(default='violet', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_billets', to='events.event')),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
    ]
