# Generated by Django 6.1.2 on 2026-10-07 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de l'événement"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Lieu")),
                (
                    "visual",
                    models.ImageField(
                        upload_to="events/visuals/",
                        verbose_name="Visuel de l'événement",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/logos/",
                        verbose_name="Logo de l'événement",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                (
                    "purchase_deadline",
                    models.DateField(verbose_name="Date limite d'achat"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, verbose_name="Type de ticket"),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Prix (FCFA)")),
                ("stock", models.PositiveIntegerField(verbose_name="Stock")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["price", "id"],
            },
        ),
    ]
